name: "coverage"
on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Generate coverage
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r tests/requirements.txt
          python -m pytest --cov-report xml:coverage.xml --cov=perceval
      - name: Get Cover
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
